### ISSUE TITLE
Improve Navbar Hover Effect

### ISSUE THREAD

**Issue by alienx5499** [MandyMeindersma/MandyMeindersma.github.io#43]
The current hover effect on the navbar items is not intuitive and inconsistent with the overall design, making the interaction less appealing. Additionally, the footer has alignment issues across various screen sizes, where content is not centered or aligned properly, affecting the overall layout and responsiveness. I would like to enhance the navbar hover effect for smoother transitions and fix the footer alignment for better consistency. Please assign this issue to me.

**Comment by MandyMeindersma** [comment]
hey @alienx5499 this is just my personal website. It's just me creating something so I am just going to keep this repo to my own contributions for now. Thank you for the idea though!

**Comment by alienx5499** [comment]
Hi @MandyMeindersma ,

Thank you for your response! I completely understand and appreciate your approach. It’s great to see you working on your personal website and focusing on your contributions. If you ever need feedback or ideas in the future, feel free to reach out. Best of luck with your project!
